-- Data tables for admin daily & map
CREATE TABLE IF NOT EXISTS daily_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  title VARCHAR(255) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  link VARCHAR(500) NOT NULL,
  difficulty VARCHAR(32) NOT NULL DEFAULT 'green',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_date (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS map_nodes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module VARCHAR(128) NOT NULL,
  difficulty VARCHAR(32) NOT NULL DEFAULT '入门',
  title VARCHAR(255) NOT NULL,
  link VARCHAR(500) DEFAULT NULL,
  summary TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
